In [2]:
import numpy as np


# Creating an Array

In [5]:
a = np.array([[1,2,3], [2,4,6], [4, 8, 12]])
b = np.arange(1,25).reshape(4,6)
c = np.random.rand(3,3)
print ("a:", a)
print ("b:", b)
print ("c:", c)

a: [[ 1  2  3]
 [ 2  4  6]
 [ 4  8 12]]
b: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
c: [[0.77323864 0.98579286 0.86723484]
 [0.87099464 0.57909944 0.44483447]
 [0.83444088 0.03192146 0.58914744]]
