In [2]:
import numpy as np


# Creating an Array

In [8]:
a = np.array([[1,2,3], [2,4,6], [4, 8, 12]])
#this will give us an array of two dimension created with elements inserted'
print (a)

[[ 1  2  3]
 [ 2  4  6]
 [ 4  8 12]]


In [14]:
a1 = [1, 2, 3, 4]
a2 = np.array(a1)
print (a2)
#you can also create an array using list

[1 2 3 4]


In [24]:
b = np.arange(1,25)
print ("b:", b)
# you can using range function to generate an array as well

b1 = b.reshape(4,6)
print ()
print ('b1:', b1)
# you can use reshape to reshape an array

b: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

b1: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [28]:
c = np.random.rand(2,6)
print ("C:", c)
#arrays can be generated using random numbers also, 

print ()
c1 = c.reshape(3,4)
print ("C1:", c1)

C: [[0.1143312  0.57153152 0.56617117 0.29037703 0.97169966 0.6310042 ]
 [0.18113808 0.72858149 0.42668399 0.25721868 0.08796213 0.89611353]]

C1: [[0.1143312  0.57153152 0.56617117 0.29037703]
 [0.97169966 0.6310042  0.18113808 0.72858149]
 [0.42668399 0.25721868 0.08796213 0.89611353]]


In [33]:
d = np.zeros(3*3).reshape(3,3)
print (d)
# another way of creating an array

print ()
d = d+1
print (d)
#simple mathematic operations can change elements of array

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [38]:
e= np.ones(3*4,int).reshape(4,3)
print (e)
#yet Another way of creating an array
# this method gives unit matrix


[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [43]:
f = np.eye(3)
print (f)
# eye function gives you identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Different Details about Array

In [45]:
print (a)
print (a.ndim)
# gives dimensions of array, 
# An easy way to learn dimension is by looking at number of brackets []

[[ 1  2  3]
 [ 2  4  6]
 [ 4  8 12]]
2


In [53]:
print (b1)
print (b1.dtype)
#dtype gives data type of an array


print ()
b2 = b1.astype(float)
print (b2)
print (b2.dtype)
#astype can be used to change data type

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
int32

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24.]]
float64


In [56]:
print (c1)
print (c1.shape)
#shape attribute gives shape of an array


c2 = c1.reshape(4,3)
print (c2)
print (c2.shape)
# shape of an array can be changed using reshape

[[0.1143312  0.57153152 0.56617117 0.29037703]
 [0.97169966 0.6310042  0.18113808 0.72858149]
 [0.42668399 0.25721868 0.08796213 0.89611353]]
(3, 4)
[[0.1143312  0.57153152 0.56617117]
 [0.29037703 0.97169966 0.6310042 ]
 [0.18113808 0.72858149 0.42668399]
 [0.25721868 0.08796213 0.89611353]]
(4, 3)


In [60]:
print (c1)
print (c1.size)
#this gives total no. of elements in an array

print (c1.itemsize)
#this gives size of an item in an array in bits



[[0.1143312  0.57153152 0.56617117 0.29037703]
 [0.97169966 0.6310042  0.18113808 0.72858149]
 [0.42668399 0.25721868 0.08796213 0.89611353]]
12
8


In [67]:
print (a2)
print (a2.max())
#gives maximum value

print (a2.min())
#gives minimum value

print (a2.sum())
#gives sum of all values

[1 2 3 4]
4
1
10


# Mathematical Operations

In [74]:
a4 = np.array(a)
print (a4)

print ()
print (np.exp(a4))
#this will give Exponential power, e

print ()
print (np.log(a4))
# this gives log of array

print ()
print (np.log10(a4))
#this gives natural log of an array

[[ 1  2  3]
 [ 2  4  6]
 [ 4  8 12]]

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [7.38905610e+00 5.45981500e+01 4.03428793e+02]
 [5.45981500e+01 2.98095799e+03 1.62754791e+05]]

[[0.         0.69314718 1.09861229]
 [0.69314718 1.38629436 1.79175947]
 [1.38629436 2.07944154 2.48490665]]

[[0.         0.30103    0.47712125]
 [0.30103    0.60205999 0.77815125]
 [0.60205999 0.90308999 1.07918125]]


In [81]:
print (a4)

print ()
b4 = a4 + 2
print (b4)

[[ 1  2  3]
 [ 2  4  6]
 [ 4  8 12]]

[[ 3  4  5]
 [ 4  6  8]
 [ 6 10 14]]


In [87]:
print (a4)

print ()
print (np.sqrt(a4))
#this will give square root of all values

print ()
print (np.std(a4))
#this will give standard deviation of a

print ()
print (np.mean(a4))
#this will give mean of array

[[ 1  2  3]
 [ 2  4  6]
 [ 4  8 12]]

[[1.         1.41421356 1.73205081]
 [1.41421356 2.         2.44948974]
 [2.         2.82842712 3.46410162]]

3.2998316455372216

4.666666666666667


In [98]:
print (a4)

print (b4)

print (a4 + b4)
print (a4 - b4)
print (a4 * b4) # elemenet wise matrix multiplication
print (a4@b4) # row into column matrix multiplication
print (a4 / b4)
print (a4.T) # Transposes the matrix/ array

[[ 1  2  3]
 [ 2  4  6]
 [ 4  8 12]]
[[ 3  4  5]
 [ 4  6  8]
 [ 6 10 14]]
[[ 4  6  8]
 [ 6 10 14]
 [10 18 26]]
[[-2 -2 -2]
 [-2 -2 -2]
 [-2 -2 -2]]
[[  3   8  15]
 [  8  24  48]
 [ 24  80 168]]
[[ 29  46  63]
 [ 58  92 126]
 [116 184 252]]
[[0.33333333 0.5        0.6       ]
 [0.5        0.66666667 0.75      ]
 [0.66666667 0.8        0.85714286]]
[[ 1  2  4]
 [ 2  4  8]
 [ 3  6 12]]
